CREATE OR REPLACE FORCE VIEW came.vw_asistencias (persona,fecha,sesion,asistencia) AS
SELECT PERSONA.NOMPER AS PERSONA, SESION.FECHASES AS FECHA, 'SESION '||SESION.NOMSES AS SESION, SESION_DET.ASISTENCIA AS ASISTENCIA
FROM PERSONA
INNER JOIN ASIGNACION ON ASIGNACION.CODPER = PERSONA.CODPER
INNER JOIN SESION_DET ON SESION_DET.CODASIG = ASIGNACION.CODASIG
INNER JOIN SESION ON SESION.CODSES = SESION_DET.CODSES;