CREATE OR REPLACE FORCE VIEW came.vw_asistecias_demo (codasig,asistencia,nomper,apeper,tipoper,coddetprog,gendetprog,promediofinal) AS
SELECT 
    ASIGNACION.CODASIG,ASISTENCIA,
    PERSONA.NOMPER,PERSONA.APEPER, 
    PERSONA.TIPOPER,
    PROG_DET.CODDETPROG,
    PROG_DET.GENDETPROG,
    F_PROMFINAL_PROGRAMA(ASIGNACION.CODASIG, PROG_DET.CODDETPROG) AS PROMEDIOFINAL
    FROM SESION_DET 
    INNER JOIN ASIGNACION ON ASIGNACION.CODASIG = SESION_DET.CODASIG
    INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
    INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG;