CREATE OR REPLACE FORCE VIEW came.vw_birthday_program (coddetprog,nombre,imagen,fechper,edad,estado) AS
SELECT 
ASIGNACION.CODDETPROG,
UPPER(PERSONA.NOMPER||' '||PERSONA.APEPER) AS NOMBRE,
PERSONA.IMGPER AS IMAGEN,
TO_CHAR(PERSONA.FECHPER,'DD "de" month', 'NLS_DATE_LANGUAGE=SPANISH') AS FECHPER,
trunc((to_date((to_char(sysdate,'yyyy')||'-'||to_char(sysdate,'mm')||'-'||to_char(sysdate,'dd')),'yyyy-mm-dd')- PERSONA.FECHPER )/365) as edad,
'0' AS ESTADO
FROM ASIGNACION
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
WHERE TO_CHAR(sysdate , 'dd/MM') = TO_CHAR(PERSONA.FECHPER,'dd/MM') AND TIPOPER='ES' UNION
SELECT 
ASIGNACION.CODDETPROG,
UPPER(PERSONA.NOMPER||' '||PERSONA.APEPER) AS NOMBRE,
PERSONA.IMGPER AS IMAGEN,
TO_CHAR(PERSONA.FECHPER,'DD "de" month', 'NLS_DATE_LANGUAGE=SPANISH') AS FECHPER,
trunc((to_date((to_char(sysdate,'yyyy')||'-'||to_char(sysdate,'mm')||'-'||to_char(sysdate,'dd')),'yyyy-mm-dd')- PERSONA.FECHPER )/365) as edad,
'1' AS ESTADO
FROM ASIGNACION
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
WHERE TO_CHAR(sysdate +1 , 'dd/MM') = TO_CHAR(PERSONA.FECHPER,'dd/MM') AND TIPOPER='ES' UNION
SELECT 
ASIGNACION.CODDETPROG,
UPPER(PERSONA.NOMPER||' '||PERSONA.APEPER) AS NOMBRE,
PERSONA.IMGPER AS IMAGEN,
TO_CHAR(PERSONA.FECHPER,'DD "de" month', 'NLS_DATE_LANGUAGE=SPANISH') AS FECHPER,
trunc((to_date((to_char(sysdate,'yyyy')||'-'||to_char(sysdate,'mm')||'-'||to_char(sysdate,'dd')),'yyyy-mm-dd')- PERSONA.FECHPER )/365) as edad,
'2' AS ESTADO
FROM ASIGNACION
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
WHERE TO_CHAR(sysdate +2 , 'dd/MM') = TO_CHAR(PERSONA.FECHPER,'dd/MM') AND TIPOPER='ES' UNION
SELECT 
ASIGNACION.CODDETPROG,
UPPER(PERSONA.NOMPER||' '||PERSONA.APEPER) AS NOMBRE,
PERSONA.IMGPER AS IMAGEN,
TO_CHAR(PERSONA.FECHPER,'DD "de" month', 'NLS_DATE_LANGUAGE=SPANISH') AS FECHPER,
trunc((to_date((to_char(sysdate,'yyyy')||'-'||to_char(sysdate,'mm')||'-'||to_char(sysdate,'dd')),'yyyy-mm-dd')- PERSONA.FECHPER )/365) as edad,
'3' AS ESTADO
FROM ASIGNACION
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
WHERE TO_CHAR(sysdate +3 , 'dd/MM') = TO_CHAR(PERSONA.FECHPER,'dd/MM') AND TIPOPER='ES' UNION
SELECT 
ASIGNACION.CODDETPROG,
UPPER(PERSONA.NOMPER||' '||PERSONA.APEPER) AS NOMBRE,
PERSONA.IMGPER AS IMAGEN,
TO_CHAR(PERSONA.FECHPER,'DD "de" month', 'NLS_DATE_LANGUAGE=SPANISH') AS FECHPER,
trunc((to_date((to_char(sysdate,'yyyy')||'-'||to_char(sysdate,'mm')||'-'||to_char(sysdate,'dd')),'yyyy-mm-dd')- PERSONA.FECHPER )/365) as edad,
'4' AS ESTADO
FROM ASIGNACION
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
WHERE TO_CHAR(sysdate +4 , 'dd/MM') = TO_CHAR(PERSONA.FECHPER,'dd/MM') AND TIPOPER='ES' UNION
SELECT 
ASIGNACION.CODDETPROG,
UPPER(PERSONA.NOMPER||' '||PERSONA.APEPER) AS NOMBRE,
PERSONA.IMGPER AS IMAGEN,
TO_CHAR(PERSONA.FECHPER,'DD "de" month', 'NLS_DATE_LANGUAGE=SPANISH') AS FECHPER,
trunc((to_date((to_char(sysdate,'yyyy')||'-'||to_char(sysdate,'mm')||'-'||to_char(sysdate,'dd')),'yyyy-mm-dd')- PERSONA.FECHPER )/365) as edad,
'5' AS ESTADO
FROM ASIGNACION
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
WHERE TO_CHAR(sysdate +5 , 'dd/MM') = TO_CHAR(PERSONA.FECHPER,'dd/MM') AND TIPOPER='ES' UNION
SELECT 
ASIGNACION.CODDETPROG,
UPPER(PERSONA.NOMPER||' '||PERSONA.APEPER) AS NOMBRE,
PERSONA.IMGPER AS IMAGEN,
TO_CHAR(PERSONA.FECHPER,'DD "de" month', 'NLS_DATE_LANGUAGE=SPANISH') AS FECHPER,
trunc((to_date((to_char(sysdate,'yyyy')||'-'||to_char(sysdate,'mm')||'-'||to_char(sysdate,'dd')),'yyyy-mm-dd')- PERSONA.FECHPER )/365) as edad,
'6' AS ESTADO
FROM ASIGNACION
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
WHERE TO_CHAR(sysdate +6 , 'dd/MM') = TO_CHAR(PERSONA.FECHPER,'dd/MM') AND TIPOPER='ES' ORDER BY ESTADO,NOMBRE;