CREATE OR REPLACE FORCE VIEW came.vw_cbgen_prog_user (codper,codprog,gendetprog,coddetprog,estdetprog,inasistencias,programa) AS
SELECT ASIGNACION.CODPER,PROGRAMA.CODPROG,PROG_DET.GENDETPROG,PROG_DET.CODDETPROG,PROG_DET.ESTDETPROG,PROG_DET.LIMINAC AS INASISTENCIAS,
CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('G:',PROG_DET.GENDETPROG),' - '),PROGRAMA.INIPROG),' - '),PROGRAMA.NOMPROG) AS PROGRAMA 
FROM PROG_DET INNER JOIN PROGRAMA ON programa.codprog = PROG_DET.CODPROG 
INNER JOIN ASIGNACION ON ASIGNACION.CODDETPROG = PROG_DET.CODDETPROG
WHERE PROGRAMA.ESTPROG LIKE 'A';