CREATE OR REPLACE FORCE VIEW came.vw_cbgen_prog (codprog,gendetprog,coddetprog,estdetprog,estprog,codper,programa) AS
SELECT PROGRAMA.CODPROG,PROG_DET.GENDETPROG,
 PROG_DET.CODDETPROG,
 PROG_DET.ESTDETPROG,
 PROGRAMA.ESTPROG,
 prog_det.codper,
 
CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('G:',PROG_DET.GENDETPROG),' - '),PROGRAMA.INIPROG),' - '),PROGRAMA.NOMPROG) AS PROGRAMA 
 FROM PROG_DET INNER JOIN PROGRAMA ON programa.codprog = PROG_DET.CODPROG;