CREATE OR REPLACE FORCE VIEW came.vw_direc_imp_parc (codasig,codper,dniper,coddetprog,estdetprog,codprog,participante,director,estfase) AS
SELECT 
ASIGNACION.CODASIG,
DIRECTOR.CODPER,
PERSONA.DNIPER,
PROG_DET.CODDETPROG, 
PROG_DET.ESTDETPROG,
PROGRAMA.CODPROG,
PERSONA.NOMPER || ' ' || PERSONA.APEPER AS PARTICIPANTE,
DIRECTOR.NOMPER ||' ' || DIRECTOR.APEPER AS DIRECTOR, FASE.ESTFASE
FROM ASIGNACION
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER 
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN FASE ON PROG_DET.CODDETPROG = FASE.CODDETPROG
INNER JOIN PERSONA DIRECTOR ON DIRECTOR.CODPER = PROG_DET.CODPER
INNER JOIN PROGRAMA ON PROGRAMA.CODPROG = PROG_DET.CODPROG;