CREATE OR REPLACE FORCE VIEW came.vw_empresa_mantenimiento (codemp,rucemp,nombemp,codubi,diremp,actemp,ubigeo) AS
SELECT EMPRESA.CODEMP, EMPRESA.RUCEMP, EMPRESA.NOMBEMP, EMPRESA.CODUBI,
    EMPRESA.DIREMP, EMPRESA.ACTEMP, 
    UBIGEO.DEPUBI ||','|| UBIGEO.PROVUBI||','|| UBIGEO.DISTUBI AS UBIGEO
    FROM EMPRESA INNER JOIN UBIGEO ON UBIGEO.CODUBI = EMPRESA.CODUBI;