CREATE OR REPLACE FORCE VIEW came.vw_entrevista (codigo,participante,pregunta1,pregunta2,comentarios,programa) AS
SELECT ENTREVISTA.CODENT AS "CODIGO",
CONCAT(CONCAT(PERSONA.NOMPER,' '),PERSONA.APEPER) AS "PARTICIPANTE",
ENTREVISTA.PRE1 AS "PREGUNTA1",
ENTREVISTA.PRE2 AS "PREGUNTA2",
ENTREVISTA.COMENT AS "COMENTARIOS",
PROGRAMA.CODPROG AS "PROGRAMA"
FROM ENTREVISTA INNER JOIN PERSONA ON ENTREVISTA.CODPER = PERSONA.CODPER
INNER JOIN ASIGNACION ON PERSONA.CODPER = ASIGNACION.CODPER
INNER JOIN PROG_DET ON ASIGNACION.CODDETPROG = PROG_DET.CODDETPROG
INNER JOIN PROGRAMA ON PROG_DET.CODPROG = PROGRAMA.CODPROG
WHERE PERSONA.TIPOPER = 'PO' OR ASIGNACION.ESTREG = 'R' OR ASIGNACION.ESTREG = 'A';