CREATE OR REPLACE FORCE VIEW came.vw_form_impac_parc (codasig,coddetprog,persona,dniper,estdetprog,nomfase,estfase) AS
SELECT ASIGNACION.CODASIG, PROG_DET.CODDETPROG, PERSONA.NOMPER || PERSONA.APEPER AS PERSONA, PERSONA.DNIPER, PROG_DET.ESTDETPROG, FASE.NOMFASE,
FASE.ESTFASE
FROM ASIGNACION 
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
INNER JOIN FASE_DET ON FASE_DET.CODASIG = ASIGNACION.CODASIG
INNER JOIN FASE ON FASE_DET.CODFASE = FASE.CODFASE
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PROGRAMA ON PROGRAMA.CODPROG = PROG_DET.CODPROG;