CREATE OR REPLACE FORCE VIEW came.vw_imp_final_informe (coddetprog,codfase,nomfase,persona,dniper,estado,fecha) AS
SELECT DISTINCT
FASE.CODDETPROG,
FASE.CODFASE,
FASE.NOMFASE,
PERSONA.NOMPER ||' '||PERSONA.APEPER AS PERSONA,
PERSONA.DNIPER,
(SELECT CASE WHEN COUNT(*) = 1 THEN 'ENVIADO' END FROM F_IMP_FINAL WHERE CODFASE = FASE.CODFASE AND DNIPER = PERSONA.DNIPER) AS ESTADO,
(SELECT TO_CHAR(F_IMP_FINAL.FECEVAIMP,'dd/MM/YYYY') FROM F_IMP_FINAL WHERE CODFASE = FASE.CODFASE AND DNIPER = PERSONA.DNIPER) AS FECHA
FROM FASE
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = FASE.CODDETPROG
INNER JOIN ASIGNACION ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PERSONA ON ASIGNACION.CODPER = PERSONA.CODPER;