CREATE OR REPLACE FORCE VIEW came.vw_listdetprog (coddetprog,nomprog,codper,director,fechini,fechfin,gendetprog,estdetprog,frecdetprog,horinifin,liminac,nivger) AS
SELECT 
PROG_DET.CODDETPROG,
PROGRAMA.NOMPROG,
PERSONA.CODPER,
(PERSONA.APEPER||' '||PERSONA.NOMPER) AS DIRECTOR,
TO_CHAR(PROG_DET.FECHINI,'DD/MM/YYYY') AS FECHINI,
TO_CHAR(PROG_DET.FECHFIN,'DD/MM/YYYY') AS FECHFIN,
PROG_DET.GENDETPROG,
PROG_DET.ESTDETPROG,
PROG_DET.FRECDETPROG,
PROG_DET.HORINIFIN,
PROG_DET.LIMINAC,
PROG_DET.NIVGER
FROM PROGRAMA 
INNER JOIN PROG_DET ON PROGRAMA.CODPROG = PROG_DET.CODPROG
INNER JOIN PERSONA ON PROG_DET.CODPER = PERSONA.CODPER;