CREATE OR REPLACE FORCE VIEW came.vw_list_sescouch (fecha,codper,codcoach,alumno,coach) AS
SELECT TO_CHAR(COACHING.FECHA,'DD/MM/YYYY') AS FECHA,ASIGCOACH.CODPER,ASIGCOACH.CODCOACH,ALU.NOMPER||' '||ALU.APEPER AS ALUMNO ,PERSONA.NOMPER||' '||PERSONA.APEPER AS COACH  FROM COACHING 
INNER JOIN ASIGCOACH ON coaching.codasicoa = ASIGCOACH.CODASICOA 
INNER JOIN PERSONA ALU ON ALU.codper = ASIGCOACH.CODPER
INNER JOIN PERSONA ON PERSONA.CODPER= ASIGCOACH.CODCOACH;