CREATE OR REPLACE FORCE VIEW came.vw_listcoach (coach,nomprog,gendetprog,nomper,sesionesc,nombemp,fecreg,coddetprog) AS
SELECT (COACH.NOMPER || ' ' || COACH.APEPER) AS COACH,programa.nomprog,prog_det.gendetprog,
       (PERSONA.NOMPER || ' ' || PERSONA.APEPER) AS NOMPER,COUNT(PERSONA.CODPER)AS SESIONESC,empresa.nombemp,ASIGNACION.FECREG,
       ASIGNACION.CODDETPROG
FROM PERSONA
INNER JOIN EMPRESA ON empresa.codemp = persona.codemp
INNER JOIN ASIGNACION ON PERSONA.CODPER = ASIGNACION.CODPER
INNER JOIN PROG_DET ON prog_det.coddetprog =asignacion.coddetprog
INNER JOIN PROGRAMA ON programa.codprog = prog_det.codprog
LEFT OUTER JOIN ASIGCOACH ON PERSONA.CODPER = ASIGCOACH.CODPER
LEFT OUTER JOIN PERSONA COACH ON COACH.CODPER = ASIGCOACH.CODCOACH
INNER JOIN SESION_DET ON asignacion.codasig = sesion_det.codasig
WHERE (ASIGCOACH.ESTASICOA LIKE 'A' OR ASIGCOACH.ESTASICOA IS NULL) AND PERSONA.TIPOPER LIKE '%ES%'
 GROUP BY programa.nomprog,prog_det.gendetprog,PERSONA.NOMPER,PERSONA.APEPER,empresa.nombemp,ASIGNACION.FECREG,ASIGNACION.CODDETPROG,COACH.NOMPER ,COACH.APEPER
ORDER BY COACH DESC,NOMPER;