CREATE OR REPLACE FORCE VIEW came.vw_nota_sesiones (codprog,nomprog,gendetprog,codper,persona,promedios,tipses,codfase,codasig,trabajo,examparc,examfinal) AS
SELECT PROGRAMA.CODPROG, PROGRAMA.NOMPROG, PROG_DET.GENDETPROG,
 PERSONA.CODPER,
CONCAT(CONCAT(PERSONA.NOMPER, ' '), PERSONA.APEPER) AS PERSONA, 
--PERSONA.NOMPER, PERSONA.APEPER,
SESION_DET.PROMEDIOS,SESION.TIPSES,SESION.CODFASE,SESION_DET.CODASIG,SESION_DET.TRABAJO,SESION_DET.EXAMPARC,SESION_DET.EXAMFINAL 
FROM SESION_DET 
INNER JOIN SESION ON SESION_DET.CODSES = SESION.CODSES
INNER JOIN ASIGNACION ON SESION_DET.CODASIG = ASIGNACION.CODASIG
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PROGRAMA ON PROGRAMA.CODPROG = PROG_DET.CODPROG;