CREATE OR REPLACE FORCE VIEW came.vw_notas (codasig,coddetprog,codper,estper,tipoper,nombre,gendetprog,nomfase,codses) AS
SELECT 
   ASIGNACION.CODASIG,
ASIGNACION.CODDETPROG,
PERSONA.CODPER,
PERSONA.ESTPER,
PERSONA.TIPOPER,
(UPPER(TRIM(PERSONA.APEPER))||', '||INITCAP(TRIM(PERSONA.NOMPER))) AS NOMBRE,
PROG_DET.GENDETPROG,
FASE.NOMFASE,
SESION.CODSES
FROM ASIGNACION 
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN FASE ON  FASE.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN SESION ON SESION.CODFASE = FASE.CODFASE ORDER BY NOMBRE ASC;