CREATE OR REPLACE FORCE VIEW came.vw_nota_prom (coddetses,nombre,codses,asistencia,participacion,caso,caso2,control,examparc,examfinal,trabajo,promedios) AS
SELECT
SESION_DET.CODDETSES AS CODDETSES,
(UPPER(TRIM(PERSONA.APEPER))||', '||INITCAP(TRIM(PERSONA.NOMPER))) AS NOMBRE,
SESION_DET.CODSES AS CODSES,
SESION_DET.ASISTENCIA AS ASISTENCIA,
SESION_DET.PARTICIPACION AS PARTICIPACION,
SESION_DET.CASO AS CASO,
SESION_DET.CASO2 AS CASO2,
SESION_DET.CONTROL AS CONTROL,
SESION_DET.EXAMPARC AS EXAMPARC,
SESION_DET.EXAMFINAL AS EXAMFINAL,
SESION_DET.TRABAJO AS TRABAJO,
SESION_DET.PROMEDIOS AS PROMEDIOS
FROM SESION_DET
INNER JOIN ASIGNACION ON SESION_DET.CODASIG = ASIGNACION.CODASIG
INNER JOIN PERSONA ON ASIGNACION.CODPER = PERSONA.CODPER;