CREATE OR REPLACE FORCE VIEW came.vw_persona (codper,apellido,nombre,names,dniper,userper,emailper,codtp,sexo,celper,dirper,tipoper,ubigeo,estper) AS
SELECT 
CODPER,
UPPER(TRIM(PERSONA.APEPER)) AS APELLIDO , 
INITCAP(TRIM(PERSONA.NOMPER)) AS NOMBRE,
(PERSONA.APEPER ||' '|| PERSONA.NOMPER) AS NAMES,
PERSONA.DNIPER,
PERSONA.USERPER,
PERSONA.EMAILPER,
PERSONA.TIPOPER AS CODTP,
CASE
    WHEN PERSONA.SEXPER = 'M' THEN 'Masculino'
    WHEN PERSONA.SEXPER = 'F' THEN 'Femenino'
END AS SEXO,
PERSONA.CELPER,
PERSONA.DIRPER,
CASE
    WHEN PERSONA.TIPOPER = 'D' THEN 'Director'
    WHEN PERSONA.TIPOPER = 'E' THEN 'Estudiante'
    WHEN PERSONA.TIPOPER = 'P' THEN 'Profesor'
    WHEN PERSONA.TIPOPER = 'A' THEN 'Administrador'
END AS TIPOPER,
(UBIGEO.DEPUBI||','||UBIGEO.PROVUBI||','||UBIGEO.DISTUBI) AS UBIGEO,
PERSONA.ESTPER
FROM PERSONA
INNER JOIN UBIGEO on UBIGEO.CODUBI = PERSONA.CODUBI
WHERE PERSONA.TIPOPER NOT LIKE 'ES' AND PERSONA.TIPOPER NOT LIKE 'PO'
ORDER BY NOMBRE;