CREATE OR REPLACE FORCE VIEW came.vw_pagos (codigo,participante,asume,estado,descuento,condicion,observaciones,encargado,email,telefono,registro,programa) AS
SELECT PAGOS.CODPAG AS "CODIGO",
CONCAT(CONCAT(PERSONA.NOMPER,' '),PERSONA.APEPER) AS "PARTICIPANTE",
PAGOS.ASUMPAG AS "ASUME",
PAGOS.ESTPAG AS "ESTADO",
PAGOS.CANTDES AS "DESCUENTO",
PAGOS.CONDPAG AS "CONDICION",
PAGOS.OBSEPAG AS "OBSERVACIONES",
PAGOS.ENCPAG AS "ENCARGADO",
PAGOS.EMAILENC AS "EMAIL",
PAGOS.TELFENC AS "TELEFONO",
PAGOS.FECHAREG AS "REGISTRO",
PROGRAMA.CODPROG AS "PROGRAMA"
FROM PAGOS INNER JOIN PERSONA ON PAGOS.CODPER = PERSONA.CODPER
INNER JOIN ASIGNACION ON PERSONA.CODPER = ASIGNACION.CODPER
INNER JOIN PROG_DET ON ASIGNACION.CODDETPROG = PROG_DET.CODDETPROG
INNER JOIN PROGRAMA ON PROG_DET.CODPROG = PROGRAMA.CODPROG
WHERE PERSONA.TIPOPER = 'PO' OR ASIGNACION.ESTREG = 'R';