CREATE OR REPLACE FORCE VIEW came.vw_prome (codses,codasig,coddetses,promedio) AS
SELECT CODSES,CODASIG,CODDETSES,
(PARTICIPACION+ENCUESTA+CONTROL+EXAMPARC+EXAMFINAL+TRABAJO)/DIVISOR AS PROMEDIO
FROM (SELECT CODSES,CODASIG,CODDETSES ,
NVL(PARTICIPACION,0) AS PARTICIPACION,
NVL(CASO,0) AS ENCUESTA,
NVL(CONTROL,0) AS CONTROL,
NVL(EXAMPARC,0) AS EXAMPARC,
NVL(EXAMFINAL,0) AS EXAMFINAL,
NVL(TRABAJO,0) AS TRABAJO,
(SELECT VW_SESCAL.CONTADOR FROM VW_SESCAL WHERE CODSES = SESION_DET.CODSES) AS DIVISOR
FROM SESION_DET);