CREATE OR REPLACE FORCE VIEW came.vw_persona_monitor (codper,dniper,nomper,emailper,celper,nompro,coddetprog) AS
SELECT PERSONA.CODPER,
       PERSONA.DNIPER,
       (PERSONA.NOMPER || ' ' || PERSONA.APEPER) AS NOMPER,
       PERSONA.EMAILPER,
       PERSONA.CELPER,
       (MONITOR.NOMPER || ' ' || MONITOR.APEPER) AS NOMPRO,
       ASIGNACION.CODDETPROG
FROM PERSONA
INNER JOIN ASIGNACION ON PERSONA.CODPER = ASIGNACION.CODPER
LEFT OUTER JOIN ASIGMONITOR ON PERSONA.CODPER = ASIGMONITOR.CODPER
LEFT OUTER JOIN PERSONA MONITOR ON MONITOR.CODPER = ASIGMONITOR.CODMONITOR
WHERE (ASIGMONITOR.ESTASIMON LIKE 'A' OR ASIGMONITOR.ESTASIMON IS NULL) AND PERSONA.TIPOPER LIKE '%ES%'
ORDER BY NOMPRO DESC,NOMPER;