CREATE OR REPLACE FORCE VIEW came.vw_persona_asig (codper,nombre,nomprog,coddetprog) AS
SELECT PERSONA.CODPER,(PERSONA.NOMPER || ' ' || PERSONA.APEPER) as nombre , PROGRAMA.NOMPROG , ASIGNACION.CODDETPROG
FROM PERSONA
INNER JOIN ASIGNACION ON PERSONA.CODPER = ASIGNACION.CODPER
inner join PROG_DET on PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
inner join PROGRAMA on PROGRAMA.CODPROG = PROG_DET.CODPROG
WHERE PERSONA.TIPOPER LIKE 'E';