CREATE OR REPLACE FORCE VIEW came.vw_persona_coach (codper,dniper,nomper,emailper,celper,nompro,coddetprog) AS
SELECT PERSONA.CODPER,
       PERSONA.DNIPER,
       (PERSONA.NOMPER || ' ' || PERSONA.APEPER) AS NOMPER,
       PERSONA.EMAILPER,
       PERSONA.CELPER,
       (COACH.NOMPER || ' ' || COACH.APEPER) AS NOMPRO,
       ASIGNACION.CODDETPROG
FROM PERSONA
INNER JOIN ASIGNACION ON PERSONA.CODPER = ASIGNACION.CODPER
LEFT OUTER JOIN ASIGCOACH ON PERSONA.CODPER = ASIGCOACH.CODPER
LEFT OUTER JOIN PERSONA COACH ON COACH.CODPER = ASIGCOACH.CODCOACH
WHERE (ASIGCOACH.ESTASICOA LIKE 'A' OR ASIGCOACH.ESTASICOA IS NULL) AND PERSONA.TIPOPER LIKE '%ES%'
ORDER BY NOMPRO DESC,NOMPER;