CREATE OR REPLACE FORCE VIEW came.vw_parxpro (nombre,apellido,dni,programa,estado) AS
select PERSONA.NOMPER AS "NOMBRE",
PERSONA.APEPER AS "APELLIDO",
PERSONA.DNIPER AS "DNI",
ASIGNACION.CODDETPROG AS "PROGRAMA",
ASIGNACION.ESTREG AS "ESTADO"
from PERSONA INNER JOIN ASIGNACION ON PERSONA.CODPER = ASIGNACION.CODPER 
WHERE PERSONA.TIPOPER = 'PO';