CREATE OR REPLACE FORCE VIEW came.vw_rfpar_cb (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Coffee Break:' AS ITEM,
SERVRPT1 as OP,
CASE 
WHEN SERVRPT1 = '1' THEN 'Mal'
WHEN SERVRPT1 = '2' THEN 'Regular'
WHEN SERVRPT1 = '3' THEN 'Bien'
WHEN SERVRPT1 = '4' THEN 'Muy bien'
WHEN SERVRPT1 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(SERVRPT1) AS RESULTADO
FROM FPARTICIPANTE
GROUP BY SERVRPT1, 'Coffee Break:', CODSES ORDER BY ITEM,OP;