CREATE OR REPLACE FORCE VIEW came.vw_reporte_estadistico (coddetprog,fechini,fechfin,tipo_programa,certificados,participantes_inscritos,total_programa) AS
SELECT 
PROG_DET.CODDETPROG,
PROG_DET.FECHINI,
PROG_DET.FECHFIN,
TIPOPROG.NOMTIPOPG AS TIPO_PROGRAMA,
CASE WHEN (F_REPORTE_INASISTENCIA(ASIGNACION.CODASIG, PROG_DET.CODDETPROG)) <= liminac THEN 'CERTIFICA' 
WHEN (F_REPORTE_INASISTENCIA(ASIGNACION.CODASIG, PROG_DET.CODDETPROG)) > liminac THEN 'NO CERTIFICA'
END CERTIFICADOS,
(F_PARTICIPANTES_INSCITOS_V2(ESTUD.TIPOPER,TIPOPROG.CODTIPPG)) AS PARTICIPANTES_INSCRITOS,
--(NOMPER||' '||APEPER) AS INSCRITO, 
(F_TOTAL_PROGRAMAS(PROGRAMA.codprog,TIPOPROG.CODTIPPG)) AS TOTAL_PROGRAMA
FROM PROG_DET 
INNER JOIN PROGRAMA ON PROG_DET.CODPROG = PROGRAMA.CODPROG
INNER JOIN asignacion ON PROG_DET.coddetprog = asignacion.coddetprog
INNER JOIN PERSONA ESTUD ON asignacion.CODPER = ESTUD.CODPER
INNER JOIN TIPOPROG ON PROGRAMA.CODTIPPG = TIPOPROG.CODTIPPG
WHERE TIPOPER = 'ES'
--WHERE FECHINI BETWEEN '10/10/2015' AND '10/10/2018'
GROUP BY 
NOMPROG,
PROGRAMA.codprog,TIPOPROG.CODTIPPG,
PROGRAMA.CODTIPPG,
GENDETPROG,
PROG_DET.FECHINI,
TIPOPROG.CODTIPPG,
PROG_DET.FECHFIN,
TIPOPROG.NOMTIPOPG,
liminac,PROG_DET.FECHINI,PROG_DET.FECHFIN,
NOMPER,
APEPER,
ASIGNACION.CODASIG, 
PROG_DET.CODDETPROG,
TIPOPER;