CREATE OR REPLACE FORCE VIEW came.vw_report_docente_rol (codper,nombre,tipo) AS
SELECT "CODPER","NOMBRE","TIPO" FROM (SELECT CODPER, CONCAT(CONCAT(NOMPER,' '),APEPER) AS NOMBRE,
regexp_substr(TIPOPER, '[^,]+',1, 1) AS TIPO
FROM PERSONA 
UNION ALL 
SELECT CODPER, CONCAT(CONCAT(NOMPER,' '),APEPER) AS NOMBRE,
regexp_substr(TIPOPER, '[^,]+',1, 2) AS TIPO
FROM PERSONA 
UNION ALL 
SELECT CODPER, CONCAT(CONCAT(NOMPER,' '),APEPER) AS NOMBRE,
regexp_substr(TIPOPER, '[^,]+',1, 3) AS TIPO
FROM PERSONA 
UNION ALL 
SELECT CODPER, CONCAT(CONCAT(NOMPER,' '),APEPER) AS NOMBRE,
regexp_substr(TIPOPER, '[^,]+',1, 4) AS TIPO
FROM PERSONA) 
PERSONA;