CREATE OR REPLACE FORCE VIEW came.vw_report_parti_inscrip (codasig,participante,programa_emp,nomprog,tipoper,gendetprog,nomtipopg,modlprog,fechper,estciv,sexper,emailper,celper,cargoper,nombemp,codprog,coddetprog,codper) AS
SELECT 
    ASIGNACION.CODASIG,UPPER(PERSONA.NOMPER) || ' ' || UPPER(PERSONA.APEPER) AS PARTICIPANTE, PROGRAMA.CODEMP AS PROGRAMA_EMP ,
    PROGRAMA.NOMPROG,PERSONA.TIPOPER, PROG_DET.GENDETPROG,TIPOPROG.NOMTIPOPG,PROG_DET.MODLPROG,to_char(PERSONA.FECHPER,'dd/MM/yyyy') as FECHPER,PERSONA.ESTCIV,PERSONA.SEXPER,PERSONA.EMAILPER,PERSONA.CELPER,PERSONA.CARGOPER,EMPRESA.NOMBEMP, 
    PROGRAMA.CODPROG,ASIGNACION.CODDETPROG,PERSONA.CODPER
    FROM ASIGNACION 
    INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
    INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
    INNER JOIN PROGRAMA ON PROGRAMA.CODPROG = PROG_DET.CODDETPROG
    INNER JOIN EMPRESA ON PERSONA.CODEMP = EMPRESA.CODEMP
    INNER JOIN TIPOPROG ON PROGRAMA.CODTIPPG = TIPOPROG.CODTIPPG    
    WHERE PERSONA.TIPOPER LIKE 'PO' OR PERSONA.TIPOPER LIKE 'ES';