CREATE OR REPLACE FORCE VIEW came.vw_rfpar_part (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Puntualidad' AS ITEM,
AUTRPT2 as OP,
CASE 
WHEN AUTRPT2 = '1' THEN 'Nula'
WHEN AUTRPT2 = '2' THEN 'Baja'
WHEN AUTRPT2 = '3' THEN 'Media'
WHEN AUTRPT2 = '4' THEN 'Alta'
END AS OPCION,
COUNT(AUTRPT2) AS RESULTADO
FROM FPARTICIPANTE
GROUP BY AUTRPT2, 'Puntualidad', CODSES ORDER BY ITEM,OP;