CREATE OR REPLACE FORCE VIEW came.vw_rfpar_t (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Tema' AS ITEM,
TEMRPT as OP,
CASE 
WHEN TEMRPT = '1' THEN 'Mal'
WHEN TEMRPT = '2' THEN 'Regular'
WHEN TEMRPT = '3' THEN 'Bien'
WHEN TEMRPT = '4' THEN 'Muy bien'
WHEN TEMRPT = '5' THEN 'Excelente'
END AS OPCION,
COUNT(TEMRPT) AS RESULTADO
FROM FPARTICIPANTE
GROUP BY TEMRPT, 'Tema', CODSES ORDER BY ITEM,OP;