CREATE OR REPLACE FORCE VIEW came.vw_report_certifica_part (codasig,participante,codprog,coddetprog,nomprog,iniprog,gendetprog,nombemp,fechini,fechfin,promediofinal,inasistencias) AS
SELECT 
    ASIGNACION.CODASIG,UPPER(PERSONA.NOMPER) || ' ' || UPPER(PERSONA.APEPER) AS PARTICIPANTE,PROGRAMA.CODPROG,ASIGNACION.CODDETPROG,
    PROGRAMA.NOMPROG , PROGRAMA.INIPROG,PROG_DET.GENDETPROG,EMPRESA.NOMBEMP,PROG_DET.FECHINI, PROG_DET.FECHFIN,
    F_PROMFINAL_PROGRAMA(ASIGNACION.CODASIG, PROG_DET.CODDETPROG) AS PROMEDIOFINAL,
    F_REPORTE_INASISTENCIA(ASIGNACION.CODASIG, PROG_DET.CODDETPROG) AS INASISTENCIAS
    FROM ASIGNACION 
    INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
    INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
    INNER JOIN PROGRAMA ON PROGRAMA.CODPROG = PROG_DET.CODDETPROG
    INNER JOIN EMPRESA ON PROGRAMA.CODEMP = EMPRESA.CODEMP;