CREATE OR REPLACE FORCE VIEW came.vw_rfdp_pa (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Participación' AS ITEM,
PARTRPT1 as OP,
CASE 
WHEN PARTRPT1 = '1' THEN 'Mal'
WHEN PARTRPT1 = '2' THEN 'Regular'
WHEN PARTRPT1 = '3' THEN 'Bien'
WHEN PARTRPT1 = '4' THEN 'Muy bien'
WHEN PARTRPT1 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(PARTRPT1) AS RESULTADO
FROM FDPROGRAMA
GROUP BY PARTRPT1, 'Participación', CODSES UNION
SELECT 
CODSES,
'Preparación para la sesión' AS ITEM,
PARTRPT2 as OP,
CASE 
WHEN PARTRPT2 = '1' THEN 'Mal'
WHEN PARTRPT2 = '2' THEN 'Regular'
WHEN PARTRPT2 = '3' THEN 'Bien'
WHEN PARTRPT2 = '4' THEN 'Muy bien'
WHEN PARTRPT2 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(PARTRPT2) AS RESULTADO
FROM FDPROGRAMA
GROUP BY PARTRPT2, 'Preparación para la sesión', CODSES ORDER BY ITEM,OP;