CREATE OR REPLACE FORCE VIEW came.vw_report_certificacion (codasig,participante,nomprog,iniprog,gendetprog,nombemp,fechini,fechfin,promediofinal,inasistencias,codprog,coddetprog,promediofinalestado) AS
SELECT 
    CODASIG,PARTICIPANTE,NOMPROG,INIPROG,GENDETPROG,NOMBEMP,FECHINI,FECHFIN,PROMEDIOFINAL,INASISTENCIAS,CODPROG,CODDETPROG,
    CASE WHEN PROMEDIOFINAL >= 12.50 THEN 'CERTIFICA' WHEN PROMEDIOFINAL <= 12.50 THEN 'NO CERTIFICA' END PROMEDIOFINALESTADO
    FROM VW_REPORT_CERTIFICA_PART;