CREATE OR REPLACE FORCE VIEW came.vw_rfpar_p (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Profesor' AS ITEM,
PROFRPT as OP,
CASE 
WHEN PROFRPT = '1' THEN 'Mal'
WHEN PROFRPT = '2' THEN 'Regular'
WHEN PROFRPT = '3' THEN 'Bien'
WHEN PROFRPT = '4' THEN 'Muy bien'
WHEN PROFRPT = '5' THEN 'Excelente'
END AS OPCION,
COUNT(PROFRPT) AS RESULTADO
FROM FPARTICIPANTE
GROUP BY PROFRPT, 'Profesor', CODSES ORDER BY ITEM,OP;