CREATE OR REPLACE FORCE VIEW came.vw_reporte_not_participantesv2 ("N°",abrare,nombemp,frecdetprog,nomtipopg,nomprog,fechini,fechfin,horinifin,codperdirec,director,codperalum,persona,gendetprog,codprog,codfase,nomfase,codasig,coddetprog,prom_caso,prom_participacion,prom_trabajo,prom_parcial,prom_final,promedio_fases_f,"ORDEN DE MERITO") AS
SELECT  
        ROW_NUMBER() OVER(ORDER BY ROUND((F_PROM_CASOS(ASIGNACION.CODASIG,FASE.CODFASE) + F_PROM_PARTICIPACIONES(ASIGNACION.CODASIG,FASE.CODFASE) +
         F_PROM_PARCIALES(ASIGNACION.CODASIG,FASE.CODFASE) + F_PROM_FINALES(ASIGNACION.CODASIG,FASE.CODFASE)+
         F_PROM_TRABAJOS(ASIGNACION.CODASIG,FASE.CODFASE))/ (F_PESO_CASOS_F(FASE.CODFASE) + F_PESO_TRABAJOS_F(FASE.CODFASE) + 
         F_PESO_FINALES_F(FASE.CODFASE) + F_PESO_PARCIALES_F(FASE.CODFASE) + F_PESO_PARTICIPACIONES_F(FASE.CODFASE)),2) DESC ) AS "N°",area.ABRARE,empresa.NOMBEMP,FRECDETPROG,NOMTIPOPG,NOMPROG,FECHINI,FECHFIN,HORINIFIN,
        DIRE.CODPER AS CODPERDIREC,(DIRE.NOMPER||' '||INITCAP(DIRE.APEPER)) AS DIRECTOR, 
        alum.CODPER AS CODPERALUM,(ALUM.NOMPER||' '||INITCAP(ALUM.APEPER)) AS PERSONA, 
        prog_det.GENDETPROG, programa.codprog, fase.codfase, fase.nomfase,asignacion.CODASIG, PROG_DET.CODDETPROG,

        (CASE WHEN F_PESO_CASOS_F(FASE.CODFASE) LIKE '0' THEN '-'
        ELSE TO_CHAR(ROUND(F_PROM_CASOS_F(ASIGNACION.CODASIG,FASE.CODFASE),2)) END)  AS PROM_CASO,

        (CASE WHEN F_PESO_PARTICIPACIONES_F(FASE.CODFASE) LIKE '0' THEN '-'
        ELSE  TO_CHAR(ROUND(F_PROM_PARTICIPACIONES_F(ASIGNACION.CODASIG,FASE.CODFASE),2))END) AS PROM_PARTICIPACION,

        (CASE WHEN F_PESO_TRABAJOS_F(FASE.CODFASE) LIKE '0' THEN '-'
        ELSE TO_CHAR(ROUND(F_PROM_TRABAJOS_F(ASIGNACION.CODASIG,FASE.CODFASE),2))END) AS PROM_TRABAJO,

        (CASE WHEN F_PESO_PARCIALES_F(FASE.CODFASE) LIKE '0' THEN '-'
        ELSE TO_CHAR(ROUND(F_PROM_PARCIALES_F(ASIGNACION.CODASIG,FASE.CODFASE),2))END)AS PROM_PARCIAL,

        (CASE WHEN F_PESO_FINALES_F(FASE.CODFASE) LIKE '0' THEN '-' 
        ELSE TO_CHAR(ROUND(F_PROM_FINALES_F(ASIGNACION.CODASIG,FASE.CODFASE),2)) END) AS PROM_FINAL,

        ROUND((F_PROM_CASOS(ASIGNACION.CODASIG,FASE.CODFASE) + F_PROM_PARTICIPACIONES(ASIGNACION.CODASIG,FASE.CODFASE) +
         F_PROM_PARCIALES(ASIGNACION.CODASIG,FASE.CODFASE) + F_PROM_FINALES(ASIGNACION.CODASIG,FASE.CODFASE)+
         F_PROM_TRABAJOS(ASIGNACION.CODASIG,FASE.CODFASE))/ (F_PESO_CASOS_F(FASE.CODFASE) + F_PESO_TRABAJOS_F(FASE.CODFASE) + 
         F_PESO_FINALES_F(FASE.CODFASE) + F_PESO_PARCIALES_F(FASE.CODFASE) + F_PESO_PARTICIPACIONES_F(FASE.CODFASE)),2) AS PROMEDIO_FASES_F,

        ROW_NUMBER() OVER(ORDER BY ROUND((F_PROM_CASOS(ASIGNACION.CODASIG,FASE.CODFASE) + F_PROM_PARTICIPACIONES(ASIGNACION.CODASIG,FASE.CODFASE) +
         F_PROM_PARCIALES(ASIGNACION.CODASIG,FASE.CODFASE) + F_PROM_FINALES(ASIGNACION.CODASIG,FASE.CODFASE)+
         F_PROM_TRABAJOS(ASIGNACION.CODASIG,FASE.CODFASE))/ (F_PESO_CASOS_F(FASE.CODFASE) + F_PESO_TRABAJOS_F(FASE.CODFASE) + 
         F_PESO_FINALES_F(FASE.CODFASE) + F_PESO_PARCIALES_F(FASE.CODFASE) + F_PESO_PARTICIPACIONES_F(FASE.CODFASE)),2) DESC ) AS "ORDEN DE MERITO"

    FROM prog_det
    INNER JOIN programa ON prog_det.codprog = programa.codprog
    LEFT OUTER JOIN AREA ON PROGRAMA.CODARE = AREA.CODARE
    LEFT OUTER JOIN EMPRESA ON PROGRAMA.CODEMP = EMPRESA.CODEMP
    INNER JOIN TIPOPROG ON programa.codtippg = tipoprog.codtippg
    INNER JOIN fase ON prog_det.coddetprog = fase.coddetprog
    INNER JOIN asignacion ON fase.coddetprog = asignacion.coddetprog
    INNER JOIN PERSONA DIRE ON dire.codper = prog_det.codper
    INNER JOIN PERSONA ALUM ON ALUM.CODPER = ASIGNACION.CODPER;