CREATE OR REPLACE FORCE VIEW came.vw_rfdp_ser (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Instalaciones' AS ITEM,
SERVRPT1 as OP,
CASE 
WHEN SERVRPT1 = '1' THEN 'Mal'
WHEN SERVRPT1 = '2' THEN 'Regular'
WHEN SERVRPT1 = '3' THEN 'Bien'
WHEN SERVRPT1 = '4' THEN 'Muy bien'
WHEN SERVRPT1 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(SERVRPT1) AS RESULTADO
FROM FDPROGRAMA
GROUP BY SERVRPT1, 'Instalaciones', CODSES  UNION
SELECT 
CODSES,
'Coffee break' AS ITEM,
SERVRPT2 as OP,
CASE 
WHEN SERVRPT2 = '1' THEN 'Mal'
WHEN SERVRPT2 = '2' THEN 'Regular'
WHEN SERVRPT2 = '3' THEN 'Bien'
WHEN SERVRPT2 = '4' THEN 'Muy bien'
WHEN SERVRPT2 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(SERVRPT2) AS RESULTADO
FROM FDPROGRAMA
GROUP BY SERVRPT2, 'Coffee break', CODSES ORDER BY ITEM,OP;