CREATE OR REPLACE FORCE VIEW came.vw_rfdp_dp (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Se dio retroalimentación al profesor' AS ITEM,
DIRCPROGRPT1 as OP,
CASE 
WHEN DIRCPROGRPT1 = '1' THEN 'Si'
WHEN DIRCPROGRPT1 = '2' THEN 'No'
END AS OPCION,
COUNT(DIRCPROGRPT1) AS RESULTADO
FROM FDPROGRAMA
GROUP BY DIRCPROGRPT1, 'Se dio retroalimentación al profesor', CODSES UNION
SELECT 
CODSES,
'Puntualidad' AS ITEM,
DIRCPROGRPT2 as OP,
CASE 
WHEN DIRCPROGRPT2 = '1' THEN 'Si'
WHEN DIRCPROGRPT2 = '2' THEN 'No'
END AS OPCION,
COUNT(DIRCPROGRPT2) AS RESULTADO
FROM FDPROGRAMA
GROUP BY DIRCPROGRPT2, 'Puntualidad', CODSES ORDER BY ITEM,OP;