CREATE OR REPLACE FORCE VIEW came.vw_report_docente_empresa (codper,codemp,nombemp) AS
SELECT PERSONA.CODPER,PERSONA.CODEMP,EMPRESA.NOMBEMP FROM PERSONA 
INNER JOIN EMPRESA
ON EMPRESA.CODEMP = PERSONA.CODEMP;