CREATE OR REPLACE FORCE VIEW came.vw_rfdp_p (codses,item,op,opcion,resultado) AS
SELECT 
CODSES,
'Dominio del tema' AS ITEM,
PROFRPT1 as OP,
CASE 
WHEN PROFRPT1 = '1' THEN 'Mal'
WHEN PROFRPT1 = '2' THEN 'Regular'
WHEN PROFRPT1 = '3' THEN 'Bien'
WHEN PROFRPT1 = '4' THEN 'Muy bien'
WHEN PROFRPT1 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(PROFRPT1) AS RESULTADO
FROM FDPROGRAMA
GROUP BY PROFRPT1, 'Dominio del tema', CODSES UNION
SELECT 
CODSES,
'Manejo del método' AS ITEM,
PROFRPT2 as OP,
CASE 
WHEN PROFRPT2 = '1' THEN 'Mal'
WHEN PROFRPT2 = '2' THEN 'Regular'
WHEN PROFRPT2 = '3' THEN 'Bien'
WHEN PROFRPT2 = '4' THEN 'Muy bien'
WHEN PROFRPT2 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(PROFRPT2) AS RESULTADO
FROM FDPROGRAMA
GROUP BY PROFRPT2, 'Manejo del método', CODSES UNION
SELECT 
CODSES,
'Involucramiento del grupo' AS ITEM,
PROFRPT3 as OP,
CASE 
WHEN PROFRPT3 = '1' THEN 'Mal'
WHEN PROFRPT3 = '2' THEN 'Regular'
WHEN PROFRPT3 = '3' THEN 'Bien'
WHEN PROFRPT3 = '4' THEN 'Muy bien'
WHEN PROFRPT3 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(PROFRPT3) AS RESULTADO
FROM FDPROGRAMA
GROUP BY PROFRPT3, 'Involucramiento del grupo', CODSES UNION
SELECT 
CODSES,
'Calidad del material de apoyo' AS ITEM,
PROFRPT4 as OP,
CASE 
WHEN PROFRPT4 = '1' THEN 'Mal'
WHEN PROFRPT4 = '2' THEN 'Regular'
WHEN PROFRPT4 = '3' THEN 'Bien'
WHEN PROFRPT4 = '4' THEN 'Muy bien'
WHEN PROFRPT4 = '5' THEN 'Excelente'
END AS OPCION,
COUNT(PROFRPT4) AS RESULTADO
FROM FDPROGRAMA
GROUP BY PROFRPT4, 'Calidad del material de apoyo', CODSES ORDER BY ITEM,OP;