CREATE OR REPLACE FORCE VIEW came.vw_report_docente_listado (codper,nombre,tipoper,emailper,celper,fechper,profper,nomare,areatrab,hijo) AS
SELECT PERSONA.CODPER,
CONCAT(CONCAT(PERSONA.APEPER, ' '),PERSONA.NOMPER) AS NOMBRE,
PERSONA.TIPOPER,
PERSONA.EMAILPER,NVL(PERSONA.CELPER,' ') AS CELPER,PERSONA.FECHPER,NVL(PERSONA.PROFPER,' ') AS PROFPER,NVL(AREA.NOMARE,' ') AS NOMARE,
NVL(PERSONA_DET.AREATRAB,' ') AS AREATRAB,
COUNT(CASE WHEN PERSONA_HIJOS.CODPERDET like PERSONA_DET.CODPERDET THEN 1 END) AS HIJO
FROM PERSONA
INNER JOIN PERSONA_DET
ON PERSONA_DET.CODPER = PERSONA.CODPER
LEFT JOIN PERSONA_HIJOS
ON PERSONA_HIJOS.CODPERDET = PERSONA_DET.CODPERDET
LEFT JOIN AREA
ON AREA.CODARE = PERSONA.CODARE
LEFT JOIN JERARQUIA
ON JERARQUIA.CODJER = PERSONA_DET.NIVJER
AND (PERSONA_DET.NIVJER = '2')
GROUP BY PERSONA.CODPER,(CONCAT(PERSONA.APEPER, ' '),PERSONA.NOMPER),PERSONA.TIPOPER,PERSONA.EMAILPER,PERSONA.CELPER,
PERSONA.FECHPER,PERSONA.PROFPER,AREA.NOMARE,PERSONA_DET.AREATRAB;