CREATE OR REPLACE FORCE VIEW came.vw_ses_imp_parc (nomses,decses,alumno,dniper,codprog,nomprog,estprog,coddetprog,estdetprog,codfase,estfase,nomfase,codses,tipses) AS
SELECT 
SESION.NOMSES,
SESION.DECSES,
PERSONA.NOMPER ||' '|| PERSONA.APEPER AS ALUMNO,
PERSONA.DNIPER,
PROGRAMA.CODPROG,
PROGRAMA.NOMPROG,
PROGRAMA.ESTPROG,
PROG_DET.CODDETPROG,
PROG_DET.ESTDETPROG,
FASE.CODFASE,
FASE.ESTFASE,
FASE.NOMFASE,
SESION.CODSES,
SESION.TIPSES
FROM ASIGNACION
INNER JOIN PERSONA ON PERSONA.CODPER = ASIGNACION.CODPER
INNER JOIN PROG_DET ON PROG_DET.CODDETPROG = ASIGNACION.CODDETPROG
INNER JOIN PROGRAMA ON PROGRAMA.CODPROG = PROG_DET.CODPROG
INNER JOIN FASE ON FASE.CODDETPROG = PROG_DET.CODDETPROG
INNER JOIN SESION ON FASE.CODFASE = SESION.CODFASE;