CREATE OR REPLACE FORCE VIEW came.vw_sesion_form (sesion,nomses,decses,nomprog,director,profesor,fechases) AS
SELECT 
SESION,
(SELECT SESION.NOMSES FROM SESION WHERE CODSES = SESION) AS NOMSES,
(SELECT SESION.DECSES FROM SESION WHERE CODSES = SESION) AS DECSES,
(SELECT (PROGRAMA.NOMPROG|| ' - GEN: ' ||PROG_DET.GENDETPROG) FROM PROGRAMA
INNER JOIN PROG_DET ON PROGRAMA.CODPROG = PROG_DET.CODPROG
INNER JOIN FASE ON PROG_DET.CODDETPROG = FASE.CODDETPROG
INNER JOIN SESION ON SESION.CODFASE = FASE.CODFASE
WHERE CODSES = SESION)AS NOMPROG,
(SELECT 
INITCAP(NOMPER ||' '||APEPER) AS NOMBRE
FROM PERSONA WHERE CODPER =DIRECTOR) AS DIRECTOR,
(SELECT 
INITCAP(NOMPER ||' '||APEPER) AS NOMBRE
FROM PERSONA WHERE CODPER =PROFESOR) AS PROFESOR,
FECHA AS FECHASES
FROM
(SELECT 
SESION.CODSES AS SESION,
to_char(SESION.FECHASES,'Day dd "de" month "de" yyyy','nls_date_language=spanish')  AS FECHA,
SESION.CODPROF AS PROFESOR,
PROG_DET.CODPER AS DIRECTOR
FROM  PROG_DET 
INNER JOIN FASE ON PROG_DET.CODDETPROG = FASE.CODDETPROG
INNER JOIN SESION ON SESION.CODFASE = FASE.CODFASE);