CREATE OR REPLACE TRIGGER came."ASIGCOACH_TRG" 
BEFORE INSERT ON came.ASIGCOACH 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODASICOA IS NULL THEN
      SELECT ASIGCOACH_SEQ.NEXTVAL INTO :NEW.CODASICOA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/