CREATE OR REPLACE TRIGGER came."ASIGNACION_TRG" 
BEFORE INSERT ON came.ASIGNACION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODASIG IS NULL THEN
      SELECT ASIGNACION_SEQ.NEXTVAL INTO :NEW.CODASIG FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/