CREATE OR REPLACE TRIGGER came."AUDITORIA_TRG" 
BEFORE INSERT ON came.AUDITORIA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODAUD IS NULL THEN
      SELECT AUDITORIA_SEQ.NEXTVAL INTO :NEW.CODAUD FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/