CREATE OR REPLACE TRIGGER came."COACHING_TRG" 
BEFORE INSERT ON came.COACHING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODCOA IS NULL THEN
      SELECT COACHING_SEQ.NEXTVAL INTO :NEW.CODCOA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/