CREATE OR REPLACE TRIGGER came."COMPETENCIA_TRG" 
BEFORE INSERT ON came.COMPETENCIA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODCOM IS NULL THEN
      SELECT COMPETENCIA_SEQ.NEXTVAL INTO :NEW.CODCOM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/