CREATE OR REPLACE TRIGGER came."CONFIG_PESOS_TRG" 
BEFORE INSERT ON came.CONFIG_PESOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODCONFPES IS NULL THEN
      SELECT CONFIG_PESOS_SEQ.NEXTVAL INTO :NEW.CODCONFPES FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/