CREATE OR REPLACE TRIGGER came."EMPRESA_TRG" 
BEFORE INSERT ON came.EMPRESA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODEMP IS NULL THEN
      SELECT EMPRESA_SEQ.NEXTVAL INTO :NEW.CODEMP FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/