CREATE OR REPLACE TRIGGER came."ENTREVISTA_TRG" 
BEFORE INSERT ON came.ENTREVISTA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODENT IS NULL THEN
      SELECT ENTREVISTA_SEQ.NEXTVAL INTO :NEW.CODENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/