CREATE OR REPLACE TRIGGER came."F_IMP_PARC_TRG" 
BEFORE INSERT ON came.F_IMP_PARC 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODIMPPARC IS NULL THEN
      SELECT F_IMP_PARC_SEQ.NEXTVAL INTO :NEW.CODIMPPARC FROM SYS.DUAL;
    END IF;
    IF INSERTING AND :NEW.RPTA03 IS NULL THEN
      SELECT F_IMP_PARC_SEQ.NEXTVAL INTO :NEW.RPTA03 FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/