CREATE OR REPLACE TRIGGER came."F_IMP_PARC_PROF_TRG" 
BEFORE INSERT ON came.F_IMP_PARC_PROF 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODIMPPARPROF IS NULL THEN
      SELECT F_IMP_PARC_PROF_SEQ.NEXTVAL INTO :NEW.CODIMPPARPROF FROM SYS.DUAL;
    END IF;
    IF INSERTING AND :NEW.CODSES IS NULL THEN
      SELECT F_IMP_PARC_PROF_SEQ.NEXTVAL INTO :NEW.CODSES FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/