CREATE OR REPLACE TRIGGER came."FASE_DET_TRG" 
BEFORE INSERT ON came.FASE_DET 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODFASDET IS NULL THEN
      SELECT FASE_DET_SEQ.NEXTVAL INTO :NEW.CODFASDET FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/