CREATE OR REPLACE TRIGGER came."FPARTICIPANTE_TRG" 
BEFORE INSERT ON came.FPARTICIPANTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COD_FPART IS NULL THEN
      SELECT FPARTICIPANTE_SEQ.NEXTVAL INTO :NEW.COD_FPART FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/