CREATE OR REPLACE TRIGGER came."FPROFESOR_TRG" 
BEFORE INSERT ON came.FPROFESOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COD_FPROF IS NULL THEN
      SELECT FPROFESOR_SEQ.NEXTVAL INTO :NEW.COD_FPROF FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/