CREATE OR REPLACE TRIGGER came."NOTIFICACION_TRG" 
BEFORE INSERT ON came.NOTIFICACION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODNOT IS NULL THEN
      SELECT NOTIFICACION_SEQ.NEXTVAL INTO :NEW.CODNOT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/