CREATE OR REPLACE TRIGGER came."PAGOS_DET_TRG" 
BEFORE INSERT ON came.PAGOS_DET 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODPAGDET IS NULL THEN
      SELECT PAGOS_DET_SEQ.NEXTVAL INTO :NEW.CODPAGDET FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/