CREATE OR REPLACE TRIGGER came."PAGOS_TRG" 
BEFORE INSERT ON came.PAGOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODPAG IS NULL THEN
      SELECT PAGOS_SEQ.NEXTVAL INTO :NEW.CODPAG FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/