CREATE OR REPLACE TRIGGER came."PERSONA_HIJOS_TRG" 
BEFORE INSERT ON came.PERSONA_HIJOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODHIJ IS NULL THEN
      SELECT PERSONA_HIJOS_SEQ.NEXTVAL INTO :NEW.CODHIJ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/