CREATE OR REPLACE TRIGGER came."PROGRAMA_TRG" 
BEFORE INSERT ON came.PROGRAMA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODPROG IS NULL THEN
      SELECT PROGRAMA_SEQ.NEXTVAL INTO :NEW.CODPROG FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/