CREATE OR REPLACE TRIGGER came."PROG_DET_TRG" 
BEFORE INSERT ON came.PROG_DET 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODDETPROG IS NULL THEN
      SELECT PROG_DET_SEQ.NEXTVAL INTO :NEW.CODDETPROG FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/