CREATE OR REPLACE TRIGGER came."SESION_ACT_TRG" 
BEFORE INSERT ON came.SESION_ACT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODSESACT IS NULL THEN
      SELECT SESION_ACT_SEQ.NEXTVAL INTO :NEW.CODSESACT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/