CREATE OR REPLACE TRIGGER came."SESION_ANEXO_TRG" 
BEFORE INSERT ON came.SESION_ANEXO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODSESANE IS NULL THEN
      SELECT SESION_ANEXO_SEQ.NEXTVAL INTO :NEW.CODSESANE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/