CREATE OR REPLACE TRIGGER came."TIPOPROG_TRG" 
BEFORE INSERT ON came.TIPOPROG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODTIPPG IS NULL THEN
      SELECT TIPOPROG_SEQ.NEXTVAL INTO :NEW.CODTIPPG FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/