CREATE OR REPLACE FUNCTION came.F_PARTICIPANTE_ASISTENCIA (persona IN PERSONA.NOMPER%TYPE)
  RETURN VARCHAR2
 IS
    asistencia SESION_DET.PARTICIPACION%TYPE;
  BEGIN     
   SELECT COUNT(SESION_DET.ASISTENCIA) INTO asistencia FROM PERSONA
        INNER JOIN ASIGNACION ON ASIGNACION.CODPER = PERSONA.CODPER
        INNER JOIN SESION_DET ON SESION_DET.CODASIG = ASIGNACION.CODASIG
        WHERE PERSONA.NOMPER = persona AND SESION_DET.ASISTENCIA LIKE 1;
        RETURN (asistencia);
  END F_PARTICIPANTE_ASISTENCIA;
/