CREATE OR REPLACE FUNCTION came.F_PARTICIPANTES_CERTIFICADOS (PARTCERTIFICA VARCHAR2) RETURN VARCHAR2
IS
CERTIFICADO NUMBER;
BEGIN
SELECT
CASE 
WHEN (F_REPORTE_INASISTENCIA(ASIGNACION.CODASIG, PROG_DET.CODDETPROG)) <= liminac THEN 'CERTIFICA' 
WHEN (F_REPORTE_INASISTENCIA(ASIGNACION.CODASIG, PROG_DET.CODDETPROG)) > liminac THEN 'NO CERTIFICA'
END CERTIFICADOS INTO CERTIFICADO
FROM PROG_DET  
INNER JOIN PROGRAMA ON PROG_DET.CODPROG = PROGRAMA.CODPROG
INNER JOIN asignacion ON PROG_DET.coddetprog = asignacion.coddetprog
INNER JOIN PERSONA ESTUD ON asignacion.CODPER = ESTUD.CODPER
INNER JOIN TIPOPROG ON PROGRAMA.CODTIPPG = TIPOPROG.CODTIPPG
WHERE TIPOPER = 'ES';
RETURN CERTIFICADO;
END F_PARTICIPANTES_CERTIFICADOS;
/