CREATE OR REPLACE FUNCTION came."F_PROMEDIO_SESIONES" (CodigoFase NUMBER, CodigoAsignacion INTEGER) Return Varchar2 Is
    CantidadSesiones FLOAT;
    CantidadControles FLOAT;
    PromedioCaso FLOAT;
    PromedioControles FLOAT;
    PromedioParticipacion FLOAT;
Begin 
        SELECT COUNT(NOMSES) INTO CantidadSesiones FROM SESION WHERE CODFASE = CodigoFase;
        SELECT AVG(SESION_DET.PARTICIPACION) INTO PromedioParticipacion FROM SESION_DET INNER JOIN SESION ON SESION_DET.CODSES = SESION.CODSES  WHERE SESION.TIPSES LIKE '%S%' AND SESION_DET.CODASIG = CodigoAsignacion AND SESION.CODFASE = CodigoFase;
        SELECT (SUM(CASE WHEN TIPSES LIKE '%C%' THEN 1 ELSE 0 END)) INTO CantidadControles  FROM SESION WHERE CODFASE = CodigoFase;
        SELECT AVG(case when SESION.TIPSES LIKE '%S2%' THEN ((SESION_DET.CASO + SESION_DET.CASO2)/2) ELSE SESION_DET.CASO end) INTO PromedioCaso  FROM SESION_DET INNER JOIN SESION ON SESION_DET.CODSES = SESION.CODSES  WHERE SESION_DET.CODASIG = CodigoAsignacion AND SESION.CODFASE = CodigoFase;
        SELECT CASE WHEN AVG(SESION_DET.CONTROL) IS NULL THEN  0 ELSE AVG(SESION_DET.CONTROL) END INTO PromedioControles FROM SESION_DET INNER JOIN SESION ON SESION_DET.CODSES = SESION.CODSES WHERE SESION_DET.CODASIG = CodigoAsignacion AND SESION.CODFASE = CodigoFase AND TIPSES LIKE '%C%';
    Return ROUND(((PromedioCaso + PromedioParticipacion + (PromedioControles * (CantidadControles / CantidadSesiones))) / (2 + (CantidadControles / CantidadSesiones))),2);
End F_PROMEDIO_SESIONES;
/